In [32]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [2]:

wafers = pd.read_csv("./wafer_fault.csv")
wafers.head()

,Sensor-1,Sensor-2,Sensor-3,Sensor-4,Sensor-5,Sensor-6,Sensor-7,Sensor-8,Sensor-9,Sensor-10,...,Sensor-582,Sensor-583,Sensor-584,Sensor-585,Sensor-586,Sensor-587,Sensor-588,Sensor-589,Sensor-590,Good/Bad
0,2968.33,2476.58,2216.7333,1748.0885,1.1127,100.0,97.5822,0.1242,1.5300,-0.0279,...,NaN,0.5004,0.0120,0.0033,2.4069,0.0545,0.0184,0.0055,33.7876,-1.0
1,2961.04,2506.43,2170.0666,1364.5157,1.5447,100.0,96.7700,0.1230,1.3953,0.0084,...,NaN,0.4994,0.0115,0.0031,2.3020,0.0545,0.0184,0.0055,33.7876,1.0
2,3072.03,2500.68,2205.7445,1363.1048,1.0518,100.0,101.8644,0.1220,1.3896,0.0138,...,NaN,0.4987,0.0118,0.0036,2.3719,0.0545,0.0184,0.0055,33.7876,-1.0
3,3021.83,2419.83,2205.7445,1363.1048,1.0518,100.0,101.8644,0.1220,1.4108,-0.0046,...,NaN,0.4934,0.0123,0.0040,2.4923,0.0545,0.0184,0.0055,33.7876,-1.0
4,3006.95,2435.34,2189.8111,1084.6502,1.1993,100.0,104.8856,0.1234,1.5094,-0.0046,...,NaN,0.4987,0.0145,0.0041,2.8991,0.0545,0.0184,0.0055,33.7876,-1.0

In [3]:
from sklearn.model_selection import train_test_split
wafers, wafers_test = train_test_split(wafers, test_size=.20, random_state=42)

In [4]:
wafers_test.shape

(100, 591)

In [5]:
wafers.describe()

,Sensor-1,Sensor-2,Sensor-3,Sensor-4,Sensor-5,Sensor-6,Sensor-7,Sensor-8,Sensor-9,Sensor-10,...,Sensor-582,Sensor-583,Sensor-584,Sensor-585,Sensor-586,Sensor-587,Sensor-588,Sensor-589,Sensor-590,Good/Bad
count,398.000000,400.0000,390.000000,390.000000,390.000000,390.0,390.000000,390.000000,400.000000,400.000000,...,139.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000
mean,3019.724623,2487.5896,2201.396420,1471.571127,1.181937,100.0,97.432942,0.122207,1.462274,0.000462,...,70.110220,0.499514,0.013564,0.003530,2.716481,0.023630,0.014976,0.004713,77.555620,-0.870000
std,71.278476,65.8749,30.186308,455.000075,0.344812,0.0,5.569791,0.002004,0.072558,0.010657,...,38.349727,0.003439,0.004279,0.000851,0.862347,0.012027,0.007600,0.002547,55.132147,0.493669
min,2825.670000,2254.9900,2114.666700,978.783200,0.753100,100.0,83.423300,0.116000,1.317900,-0.027900,...,20.309100,0.492500,0.007600,0.002100,1.515200,0.009900,0.004800,0.001700,20.309100,-1.000000
25%,2973.560000,2445.2000,2189.811100,1110.545300,0.837300,100.0,95.108900,0.120800,1.408000,-0.006800,...,46.709200,0.497300,0.011300,0.003100,2.270425,0.013400,0.009500,0.002700,33.787600,-1.000000
50%,3005.360000,2493.8900,2200.955600,1242.842000,1.162000,100.0,99.513300,0.122100,1.454200,0.001000,...,65.036500,0.499400,0.012800,0.003400,2.554900,0.021800,0.013900,0.003900,65.036500,-1.000000
75%,3072.030000,2528.5000,2213.211100,1942.306900,1.383000,100.0,101.457800,0.123400,1.508400,0.009000,...,91.985450,0.501600,0.014700,0.003800,2.949800,0.028100,0.019200,0.005900,104.303400,-1.000000
max,3221.210000,2664.5200,2315.266700,2363.641200,2.207300,100.0,107.152200,0.126200,1.641100,0.025000,...,223.101800,0.508700,0.043700,0.008900,8.816000,0.054500,0.040100,0.015000,223.101800,1.000000

In [6]:
wafers["Good/Bad"].value_counts()

-1.0    374
 1.0     26
Name: Good/Bad, dtype: int64

In [7]:
wafers["Good/Bad"].isna()

249    False
433    False
19     False
322    False
332    False
       ...
106    False
270    False
348    False
435    False
102    False
Name: Good/Bad, Length: 400, dtype: bool

In [8]:
wafers["Good/Bad"].isna().sum()

0

In [9]:
wafers

,Sensor-1,Sensor-2,Sensor-3,Sensor-4,Sensor-5,Sensor-6,Sensor-7,Sensor-8,Sensor-9,Sensor-10,...,Sensor-582,Sensor-583,Sensor-584,Sensor-585,Sensor-586,Sensor-587,Sensor-588,Sensor-589,Sensor-590,Good/Bad
249,2998.89,2532.66,2189.3556,2363.6412,2.1415,100.0,83.4233,0.1246,1.4108,0.0095,...,NaN,0.5022,0.0097,0.0027,1.9367,0.0147,0.0095,0.0028,65.0365,-1.0
433,3007.75,2535.14,2216.5000,1111.5436,0.8373,100.0,99.9867,0.1205,1.4503,0.0149,...,NaN,0.4948,0.0099,0.0032,1.9956,0.0133,0.0139,0.0038,104.3034,-1.0
19,2893.07,2596.63,2214.2889,988.2071,1.2513,100.0,101.7044,0.1209,1.4612,-0.0052,...,47.2136,0.5025,0.0118,0.0033,2.3382,0.0364,0.0172,0.0063,47.2136,-1.0
322,3001.26,2519.92,2224.6778,1308.6479,1.3907,100.0,101.1333,0.1208,1.5172,-0.0135,...,48.4818,0.4959,0.0142,0.0037,2.8609,0.0278,0.0135,0.0042,48.4818,-1.0
332,2919.71,2420.32,2134.7445,1244.2899,1.1827,100.0,99.5133,0.1249,1.3331,-0.0126,...,NaN,0.4938,0.0106,0.0028,2.1418,0.0220,0.0143,0.0045,65.2186,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,3072.03,2500.68,2205.7445,1363.1048,1.0518,100.0,101.8644,0.1220,1.3896,0.0138,...,NaN,0.4987,0.0118,0.0036,2.3719,0.0545,0.0184,0.0055,33.7876,-1.0
270,3066.38,2473.10,2171.5000,1028.4440,0.7899,100.0,101.5122,0.1224,1.3623,-0.0076,...,NaN,0.4998,0.0102,0.0031,2.0450,0.0218,0.0054,0.0020,24.6547,-1.0
348,3073.25,2440.08,2240.8666,2048.2566,1.1620,100.0,86.3822,0.1233,1.5960,0.0023,...,NaN,0.4995,0.0139,0.0041,2.7866,0.0147,0.0095,0.0028,65.0365,-1.0
435,2964.63,2494.75,NaN,NaN,NaN,NaN,NaN,NaN,1.4646,0.0021,...,NaN,0.5019,0.0128,0.0036,2.5549,0.0280,0.0078,0.0022,27.7601,-1.0
102,3018.80,2440.93,2195.6667,1333.7299,1.0772,100.0,98.9844,0.1223,1.6063,-0.0020,...,NaN,0.4994,0.0125,0.0033,2.5112,0.0278,0.0135,0.0042,48.4818,-1.0

In [10]:
wafers.isna().sum().sum()

9325

In [11]:
wafers.isna().sum()

Sensor-1       2
Sensor-2       0
Sensor-3      10
Sensor-4      10
Sensor-5      10
              ..
Sensor-587     0
Sensor-588     0
Sensor-589     0
Sensor-590     0
Good/Bad       0
Length: 591, dtype: int64

In [12]:
wafers.shape

(400, 591)

In [13]:
wafers.shape[0]

400

In [14]:
def get_cols_with_zero_std_dev(df: pd.DataFrame):
    cols_to_drop = []
    num_cols = [col for col in df.columns if df[col].dtype != 'O']  
    for col in num_cols:
        if df[col].std() == 0:
            cols_to_drop.append(col)
    return cols_to_drop

def get_redundant_cols(df: pd.DataFrame, missing_thresh=.7):
    cols_missing_ratios = df.isna().sum().div(df.shape[0])
    cols_to_drop = list(cols_missing_ratios[cols_missing_ratios > missing_thresh].index)
    return cols_to_drop

In [15]:

cols_to_drop_1 = get_redundant_cols(wafers, missing_thresh=.7)
cols_to_drop_1

['Sensor-158', 'Sensor-159', 'Sensor-293', 'Sensor-294']

In [16]:

cols_to_drop_2 = get_cols_with_zero_std_dev(df=wafers)
cols_to_drop_2

['Sensor-6',
 'Sensor-14',
 'Sensor-43',
 'Sensor-50',
 'Sensor-53',
 'Sensor-70',
 'Sensor-75',
 'Sensor-98',
 'Sensor-142',
 'Sensor-150',
 'Sensor-179',
 'Sensor-180',
 'Sensor-187',
 'Sensor-190',
 'Sensor-191',
 'Sensor-192',
 'Sensor-193',
 'Sensor-194',
 'Sensor-195',
 'Sensor-207',
 'Sensor-210',
 'Sensor-227',
 'Sensor-230',
 'Sensor-231',
 'Sensor-232',
 'Sensor-233',
 'Sensor-234',
 'Sensor-235',
 'Sensor-236',
 'Sensor-237',
 'Sensor-238',
 'Sensor-241',
 'Sensor-242',
 'Sensor-243',
 'Sensor-244',
 'Sensor-257',
 'Sensor-258',
 'Sensor-259',
 'Sensor-260',
 'Sensor-261',
 'Sensor-262',
 'Sensor-263',
 'Sensor-264',
 'Sensor-265',
 'Sensor-266',
 'Sensor-267',
 'Sensor-277',
 'Sensor-285',
 'Sensor-314',
 'Sensor-315',
 'Sensor-316',
 'Sensor-323',
 'Sensor-326',
 'Sensor-327',
 'Sensor-328',
 'Sensor-329',
 'Sensor-330',
 'Sensor-331',
 'Sensor-343',
 'Sensor-348',
 'Sensor-365',
 'Sensor-370',
 'Sensor-371',
 'Sensor-372',
 'Sensor-373',
 'Sensor-374',
 'Sensor-375',
 'Sensor-376',
 'Sensor-379',
 'Sensor-380',
 'Sensor-381',
 'Sensor-382',
 'Sensor-395',
 'Sensor-396',
 'Sensor-397',
 'Sensor-398',
 'Sensor-399',
 'Sensor-400',
 'Sensor-401',
 'Sensor-402',
 'Sensor-403',
 'Sensor-404',
 'Sensor-405',
 'Sensor-415',
 'Sensor-423',
 'Sensor-450',
 'Sensor-451',
 'Sensor-452',
 'Sensor-459',
 'Sensor-462',
 'Sensor-463',
 'Sensor-464',
 'Sensor-465',
 'Sensor-466',
 'Sensor-467',
 'Sensor-479',
 'Sensor-482',
 'Sensor-499',
 'Sensor-502',
 'Sensor-503',
 'Sensor-504',
 'Sensor-505',
 'Sensor-506',
 'Sensor-507',
 'Sensor-508',
 'Sensor-509',
 'Sensor-510',
 'Sensor-513',
 'Sensor-514',
 'Sensor-515',
 'Sensor-516',
 'Sensor-529',
 'Sensor-530',
 'Sensor-531',
 'Sensor-532',
 'Sensor-533',
 'Sensor-534',
 'Sensor-535',
 'Sensor-536',
 'Sensor-537',
 'Sensor-538',
 'Sensor-539']

In [17]:
cols_to_drop = cols_to_drop_1 + cols_to_drop_2

In [18]:
cols_to_drop

['Sensor-158',
 'Sensor-159',
 'Sensor-293',
 'Sensor-294',
 'Sensor-6',
 'Sensor-14',
 'Sensor-43',
 'Sensor-50',
 'Sensor-53',
 'Sensor-70',
 'Sensor-75',
 'Sensor-98',
 'Sensor-142',
 'Sensor-150',
 'Sensor-179',
 'Sensor-180',
 'Sensor-187',
 'Sensor-190',
 'Sensor-191',
 'Sensor-192',
 'Sensor-193',
 'Sensor-194',
 'Sensor-195',
 'Sensor-207',
 'Sensor-210',
 'Sensor-227',
 'Sensor-230',
 'Sensor-231',
 'Sensor-232',
 'Sensor-233',
 'Sensor-234',
 'Sensor-235',
 'Sensor-236',
 'Sensor-237',
 'Sensor-238',
 'Sensor-241',
 'Sensor-242',
 'Sensor-243',
 'Sensor-244',
 'Sensor-257',
 'Sensor-258',
 'Sensor-259',
 'Sensor-260',
 'Sensor-261',
 'Sensor-262',
 'Sensor-263',
 'Sensor-264',
 'Sensor-265',
 'Sensor-266',
 'Sensor-267',
 'Sensor-277',
 'Sensor-285',
 'Sensor-314',
 'Sensor-315',
 'Sensor-316',
 'Sensor-323',
 'Sensor-326',
 'Sensor-327',
 'Sensor-328',
 'Sensor-329',
 'Sensor-330',
 'Sensor-331',
 'Sensor-343',
 'Sensor-348',
 'Sensor-365',
 'Sensor-370',
 'Sensor-371',
 'Sensor-372',
 'Sensor-373',
 'Sensor-374',
 'Sensor-375',
 'Sensor-376',
 'Sensor-379',
 'Sensor-380',
 'Sensor-381',
 'Sensor-382',
 'Sensor-395',
 'Sensor-396',
 'Sensor-397',
 'Sensor-398',
 'Sensor-399',
 'Sensor-400',
 'Sensor-401',
 'Sensor-402',
 'Sensor-403',
 'Sensor-404',
 'Sensor-405',
 'Sensor-415',
 'Sensor-423',
 'Sensor-450',
 'Sensor-451',
 'Sensor-452',
 'Sensor-459',
 'Sensor-462',
 'Sensor-463',
 'Sensor-464',
 'Sensor-465',
 'Sensor-466',
 'Sensor-467',
 'Sensor-479',
 'Sensor-482',
 'Sensor-499',
 'Sensor-502',
 'Sensor-503',
 'Sensor-504',
 'Sensor-505',
 'Sensor-506',
 'Sensor-507',
 'Sensor-508',
 'Sensor-509',
 'Sensor-510',
 'Sensor-513',
 'Sensor-514',
 'Sensor-515',
 'Sensor-516',
 'Sensor-529',
 'Sensor-530',
 'Sensor-531',
 'Sensor-532',
 'Sensor-533',
 'Sensor-534',
 'Sensor-535',
 'Sensor-536',
 'Sensor-537',
 'Sensor-538',
 'Sensor-539']

In [19]:
wafers.head()

,Sensor-1,Sensor-2,Sensor-3,Sensor-4,Sensor-5,Sensor-6,Sensor-7,Sensor-8,Sensor-9,Sensor-10,...,Sensor-582,Sensor-583,Sensor-584,Sensor-585,Sensor-586,Sensor-587,Sensor-588,Sensor-589,Sensor-590,Good/Bad
249,2998.89,2532.66,2189.3556,2363.6412,2.1415,100.0,83.4233,0.1246,1.4108,0.0095,...,NaN,0.5022,0.0097,0.0027,1.9367,0.0147,0.0095,0.0028,65.0365,-1.0
433,3007.75,2535.14,2216.5000,1111.5436,0.8373,100.0,99.9867,0.1205,1.4503,0.0149,...,NaN,0.4948,0.0099,0.0032,1.9956,0.0133,0.0139,0.0038,104.3034,-1.0
19,2893.07,2596.63,2214.2889,988.2071,1.2513,100.0,101.7044,0.1209,1.4612,-0.0052,...,47.2136,0.5025,0.0118,0.0033,2.3382,0.0364,0.0172,0.0063,47.2136,-1.0
322,3001.26,2519.92,2224.6778,1308.6479,1.3907,100.0,101.1333,0.1208,1.5172,-0.0135,...,48.4818,0.4959,0.0142,0.0037,2.8609,0.0278,0.0135,0.0042,48.4818,-1.0
332,2919.71,2420.32,2134.7445,1244.2899,1.1827,100.0,99.5133,0.1249,1.3331,-0.0126,...,NaN,0.4938,0.0106,0.0028,2.1418,0.0220,0.0143,0.0045,65.2186,-1.0

In [20]:
X, y = wafers.drop(cols_to_drop, axis=1), wafers[["Good/Bad"]]

In [21]:
X

,Sensor-1,Sensor-2,Sensor-3,Sensor-4,Sensor-5,Sensor-7,Sensor-8,Sensor-9,Sensor-10,Sensor-11,...,Sensor-582,Sensor-583,Sensor-584,Sensor-585,Sensor-586,Sensor-587,Sensor-588,Sensor-589,Sensor-590,Good/Bad
249,2998.89,2532.66,2189.3556,2363.6412,2.1415,83.4233,0.1246,1.4108,0.0095,-0.0026,...,NaN,0.5022,0.0097,0.0027,1.9367,0.0147,0.0095,0.0028,65.0365,-1.0
433,3007.75,2535.14,2216.5000,1111.5436,0.8373,99.9867,0.1205,1.4503,0.0149,0.0010,...,NaN,0.4948,0.0099,0.0032,1.9956,0.0133,0.0139,0.0038,104.3034,-1.0
19,2893.07,2596.63,2214.2889,988.2071,1.2513,101.7044,0.1209,1.4612,-0.0052,-0.0130,...,47.2136,0.5025,0.0118,0.0033,2.3382,0.0364,0.0172,0.0063,47.2136,-1.0
322,3001.26,2519.92,2224.6778,1308.6479,1.3907,101.1333,0.1208,1.5172,-0.0135,0.0070,...,48.4818,0.4959,0.0142,0.0037,2.8609,0.0278,0.0135,0.0042,48.4818,-1.0
332,2919.71,2420.32,2134.7445,1244.2899,1.1827,99.5133,0.1249,1.3331,-0.0126,0.0076,...,NaN,0.4938,0.0106,0.0028,2.1418,0.0220,0.0143,0.0045,65.2186,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,3072.03,2500.68,2205.7445,1363.1048,1.0518,101.8644,0.1220,1.3896,0.0138,0.0000,...,NaN,0.4987,0.0118,0.0036,2.3719,0.0545,0.0184,0.0055,33.7876,-1.0
270,3066.38,2473.10,2171.5000,1028.4440,0.7899,101.5122,0.1224,1.3623,-0.0076,0.0112,...,NaN,0.4998,0.0102,0.0031,2.0450,0.0218,0.0054,0.0020,24.6547,-1.0
348,3073.25,2440.08,2240.8666,2048.2566,1.1620,86.3822,0.1233,1.5960,0.0023,0.0084,...,NaN,0.4995,0.0139,0.0041,2.7866,0.0147,0.0095,0.0028,65.0365,-1.0
435,2964.63,2494.75,NaN,NaN,NaN,NaN,NaN,1.4646,0.0021,0.0059,...,NaN,0.5019,0.0128,0.0036,2.5549,0.0280,0.0078,0.0022,27.7601,-1.0
102,3018.80,2440.93,2195.6667,1333.7299,1.0772,98.9844,0.1223,1.6063,-0.0020,0.0066,...,NaN,0.4994,0.0125,0.0033,2.5112,0.0278,0.0135,0.0042,48.4818,-1.0

In [22]:
y

     Good/Bad
249      -1.0
433      -1.0
19       -1.0
322      -1.0
332      -1.0
..        ...
106      -1.0
270      -1.0
348      -1.0
435      -1.0
102      -1.0

[400 rows x 1 columns]

In [23]:

print( X.shape)
X.head()
# X=X.iloc[40:50,:]

(400, 465)

,Sensor-1,Sensor-2,Sensor-3,Sensor-4,Sensor-5,Sensor-7,Sensor-8,Sensor-9,Sensor-10,Sensor-11,...,Sensor-582,Sensor-583,Sensor-584,Sensor-585,Sensor-586,Sensor-587,Sensor-588,Sensor-589,Sensor-590,Good/Bad
249,2998.89,2532.66,2189.3556,2363.6412,2.1415,83.4233,0.1246,1.4108,0.0095,-0.0026,...,NaN,0.5022,0.0097,0.0027,1.9367,0.0147,0.0095,0.0028,65.0365,-1.0
433,3007.75,2535.14,2216.5000,1111.5436,0.8373,99.9867,0.1205,1.4503,0.0149,0.0010,...,NaN,0.4948,0.0099,0.0032,1.9956,0.0133,0.0139,0.0038,104.3034,-1.0
19,2893.07,2596.63,2214.2889,988.2071,1.2513,101.7044,0.1209,1.4612,-0.0052,-0.0130,...,47.2136,0.5025,0.0118,0.0033,2.3382,0.0364,0.0172,0.0063,47.2136,-1.0
322,3001.26,2519.92,2224.6778,1308.6479,1.3907,101.1333,0.1208,1.5172,-0.0135,0.0070,...,48.4818,0.4959,0.0142,0.0037,2.8609,0.0278,0.0135,0.0042,48.4818,-1.0
332,2919.71,2420.32,2134.7445,1244.2899,1.1827,99.5133,0.1249,1.3331,-0.0126,0.0076,...,NaN,0.4938,0.0106,0.0028,2.1418,0.0220,0.0143,0.0045,65.2186,-1.0

In [24]:
print(y.shape)
y.head()
# y=y[40:50]

(400, 1)

     Good/Bad
249      -1.0
433      -1.0
19       -1.0
322      -1.0
332      -1.0

In [25]:
from sklearn.pipeline import Pipeline
from sklearn.impute import KNNImputer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

imputer = KNNImputer(n_neighbors=3)
preprocessing_pipeline = Pipeline(
    steps=[('Imputer', imputer), ('Scaler', StandardScaler())])
preprocessing_pipeline

Pipeline(steps=[('Imputer', KNNImputer(n_neighbors=3)),
                ('Scaler', StandardScaler())])

In [26]:

X_trans = preprocessing_pipeline.fit_transform(X)
print( X_trans.shape)
X_trans

(400, 465)

array([[-0.29440992,  0.68503852, -0.40518162, ..., -0.75203833,
        -0.22735916, -0.26366402],
       [-0.16965339,  0.72273278,  0.50392253, ..., -0.35891845,
         0.48576518, -0.26366402],
       [-1.78444786,  1.65733772,  0.42986968, ...,  0.62388125,
        -0.55104002, -0.26366402],
       ...,
       [ 0.75264376, -0.72211265,  1.31999425, ..., -0.75203833,
        -0.22735916, -0.26366402],
       [-0.77682062,  0.10883307, -0.01556604, ..., -0.98791025,
        -0.90433413, -0.26366402],
       [-0.01405975, -0.70919325, -0.193814  , ..., -0.2016705 ,
        -0.5280083 , -0.26366402]])

In [27]:
X, y = X_trans[:, :-1], y

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=42)

In [29]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

log_reg_clg=LogisticRegression()
svc_rbf_clf = SVC(kernel='rbf')
random_clf = RandomForestClassifier(random_state=42)
decision_tree_clf = DecisionTreeClassifier()

In [30]:
def display_scores(model,train,train_lab,test,test_lab):
    model.fit(train,train_lab)
    print(f"{model} : {model.score(test,test_lab)*100}")

In [31]:
for i in [log_reg_clg,
          svc_rbf_clf,random_clf,decision_tree_clf]:
    display_scores(i,X_train,y_train,X_test,y_test)

LogisticRegression() : 100.0
SVC() : 100.0
RandomForestClassifier(random_state=42) : 100.0
DecisionTreeClassifier() : 100.0